server:
  port: 8083

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/cart_db
  jpa:
    hibernate:
      ddl-auto: update
