server:
  port: 8084

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/order_db
  jpa:
    hibernate:
      ddl-auto: update
